version: "3.8"
services:
    lsdp-app:
        build: .
        container_name: backend
        restart: always
        ports:
          - 9000:9000
        depends_on:
          - lsdp-mongo-db
    lsdp-mongo-db:
        image: "mongo:latest"
        container_name: database
        restart: always
        volumes:
          - /data/db
